# Generated by Django 4.0.5 on 2022-06-20 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorBlocked', models.BooleanField(blank=True, default=False)),
                ('authorSubscribed', models.BooleanField(blank=True, default=False)),
                ('authorName', models.OneToOneField(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoSource', models.FileField(upload_to='')),
                ('videoRating', models.IntegerField(default=0)),
                ('videoAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=64)),
                ('commentDateTime', models.DateTimeField(auto_now_add=True)),
                ('commentRating', models.IntegerField(default=0)),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commentVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video')),
            ],
        ),
    ]
