# Generated by Django 4.0.5 on 2022-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_rename_videorating_video_videodislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoThumb',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
    ]
