# Generated by Django 4.0.5 on 2022-07-11 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0006_alter_video_videoauthor_alter_video_videosource'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='videoUsersLiked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
