# Generated by Django 4.0.5 on 2022-07-11 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0007_video_videodate_video_videousersliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoUsersDisLiked',
            field=models.ManyToManyField(related_name='UsersDisliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoUsersLiked',
            field=models.ManyToManyField(related_name='Usersliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
